spring.application.name=hr-stack

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true
spring.flyway.locations=classpath:db/migration

server.port=8080

jwt.secret=HRStackSuperSecretKeyForJWTAuthentication2026
jwt.expiration=86400000
