spring.application.name=hr-stack

# =========================
# Database
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# Flyway
# =========================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true
spring.flyway.locations=classpath:db/migration

# =========================
# Server
# =========================
server.port=8080

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# =========================
# MinIO
# =========================
minio.endpoint=${MINIO_ENDPOINT}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=salary-slips