ALTER TABLE users
    ADD COLUMN created_on BIGINT,
ADD COLUMN updated_on BIGINT;

UPDATE users
SET created_on = (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000)::BIGINT,
    updated_on = (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000)::BIGINT;

ALTER TABLE users
    ALTER COLUMN created_on SET NOT NULL,
ALTER COLUMN updated_on SET NOT NULL;